# Generated by Django 4.2.17 on 2024-12-16 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(max_length=50, verbose_name='操作行为')),
                ('method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('path', models.CharField(max_length=200, verbose_name='请求路径')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='操作地点')),
                ('browser', models.CharField(blank=True, default='', max_length=256, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, default='', max_length=256, verbose_name='操作系统')),
                ('status', models.SmallIntegerField(choices=[(1, '成功'), (0, '失败')], default=1, verbose_name='操作状态')),
                ('params', models.TextField(blank=True, default='', verbose_name='请求参数')),
                ('result', models.TextField(blank=True, default='', verbose_name='返回结果')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, default='', max_length=256, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, default='', max_length=256, verbose_name='操作系统')),
                ('device', models.CharField(blank=True, default='', max_length=256, verbose_name='设备信息')),
                ('status', models.SmallIntegerField(choices=[(1, '成功'), (0, '失败')], default=1, verbose_name='状态')),
                ('msg', models.CharField(max_length=128, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'sys_login_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=64, unique=True, verbose_name='会话标识')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, default='', max_length=256, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, default='', max_length=256, verbose_name='操作系统')),
                ('device', models.CharField(blank=True, default='', max_length=256, verbose_name='设备信息')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '在线用户',
                'verbose_name_plural': '在线用户',
                'db_table': 'sys_online_user',
                'ordering': ['-last_active_time'],
            },
        ),
    ]
