# Generated by Django 4.2.17 on 2024-12-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="配置名称"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="配置键名"
                    ),
                ),
                ("value", models.TextField(verbose_name="配置键值")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("number", "数字"),
                            ("boolean", "布尔值"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=32,
                        verbose_name="配置类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "sys_config",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="权限名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("menu", "菜单"), ("button", "按钮"), ("api", "接口")],
                        default="api",
                        max_length=32,
                        verbose_name="权限类型",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        max_length=32,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="权限代码"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="权限描述"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.permission",
                        verbose_name="父权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
                "db_table": "sys_permission",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="菜单名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CATALOG", "目录"),
                            ("MENU", "菜单"),
                            ("BUTTON", "按钮"),
                        ],
                        default="MENU",
                        max_length=32,
                        verbose_name="菜单类型",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=32, verbose_name="图标"),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="路由路径"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="组件路径"
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="权限标识"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_cache",
                    models.BooleanField(default=False, verbose_name="是否缓存"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="是否可见"),
                ),
                (
                    "is_frame",
                    models.BooleanField(default=False, verbose_name="是否外链"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.menu",
                        verbose_name="父菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
                "db_table": "sys_menu",
                "ordering": ["order"],
            },
        ),
    ]
